substitutions:
  _REGION: 'asia-northeast1'
  _AR_HOST: 'asia-northeast1-docker.pkg.dev'
  _REPO: 'trans-invert'
  _BACKEND_IMAGE: 'backend'

steps:
  # Build frontend first
  - name: 'node:18'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        echo "📦 Installing frontend dependencies..."
        cd frontend
        npm ci
        echo "🔨 Building frontend..."
        npm run build
        echo "✅ Frontend build completed"
        ls -la dist/
        echo "📂 Moving dist to root for Docker context..."
        mv dist ../frontend-dist
        ls -la ../frontend-dist/
    
  # Build Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      [
        'build',
        '-f','Dockerfile.simple',
        '-t','$_AR_HOST/$PROJECT_ID/$_REPO/$_BACKEND_IMAGE:$COMMIT_SHA',
        '.'
      ]

  # Push image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push','$_AR_HOST/$PROJECT_ID/$_REPO/$_BACKEND_IMAGE:$COMMIT_SHA']

  # Deploy to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      [
        'run','deploy','trans-invert',
        '--image','$_AR_HOST/$PROJECT_ID/$_REPO/$_BACKEND_IMAGE:$COMMIT_SHA',
        '--region','$_REGION',
        '--allow-unauthenticated',
        '--port','8000',
        '--memory','1Gi',
        '--cpu','1',
        '--min-instances','0',
        '--max-instances','10',
        '--set-env-vars','APP_ENV=production,DEBUG=false'
      ]

images:
  - '$_AR_HOST/$PROJECT_ID/$_REPO/$_BACKEND_IMAGE:$COMMIT_SHA'
