version: '3.8'
services:
  frontend:
    build: 
      context: ./frontend
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - VITE_API_URL=http://localhost:8000
    depends_on:
      - backend

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    environment:
      - APP_ENV=dev
      - APP_HOST=0.0.0.0
      - APP_PORT=8000
      - DEBUG=true
      - DEEPSEEK_API_KEY=sk-47bd8ee147164f9fa76e9c78c8dadee1
      - DEEPSEEK_BASE_URL=https://api.deepseek.com/v1
      - DEEPSEEK_MODEL=deepseek-chat
      - ALLOWED_ORIGINS=http://localhost:3000,http://127.0.0.1:3000
    command: ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]